@startuml
hide footbox
title filters owners by last name prefix
footer @generate_sequence Scenario in a .feature test
participant Browser
participant Backend
participant DB
== filters owners by last name prefix #1 ==
Browser -> Backend: GET /api/owners
activate Backend
Backend -> Backend: OwnerRepository.findByLastNameStartingWith
activate Backend
Backend -> Backend: SELECT victor.training.petclinic.domain.Owner
activate Backend
Backend -> DB: petclinic
activate DB
deactivate DB
Backend -> DB: SELECT petclinic.owners
activate DB
deactivate DB
deactivate Backend
deactivate Backend
Backend -> DB: SELECT petclinic
activate DB
deactivate DB
Backend -> DB: SELECT petclinic.visits
activate DB
deactivate DB
Backend --> Browser: 200
deactivate Backend
== filters owners by last name prefix #2 ==
Browser -> Browser: documentFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
@enduml
