@startuml
hide footbox
title orders the Name column alphabetically as it is displayed
footer @generate_sequence Scenario in a .feature test
participant Browser
Browser -> Browser: documentFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
@enduml
