@startuml
hide footbox
title owner link navigates to owner detail
footer @generate_sequence Scenario in a .feature test
participant Browser
participant Backend
participant DB
== owner link navigates to owner detail #1 ==
Browser -> Backend: GET /api/owners/{ownerId}
activate Backend
Backend -> Backend: OwnerRepository.findById
activate Backend
Backend -> Backend: Session.find victor.training.petclinic.domain.Owner
activate Backend
Backend -> DB: SELECT petclinic.owners
activate DB
deactivate DB
deactivate Backend
Backend -> Backend: Transaction.commit
activate Backend
deactivate Backend
deactivate Backend
Backend -> DB: SELECT petclinic
activate DB
deactivate DB
Backend -> DB: SELECT petclinic.visits
activate DB
deactivate DB
Backend --> Browser: 200
deactivate Backend
== owner link navigates to owner detail #2 ==
Browser -> Browser: documentFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
@enduml
