@startuml
hide footbox
title rows are sorted descending by date
footer @generate_sequence Scenario in a .feature test
participant Browser
Browser -> Browser: documentFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
Browser -> Browser: resourceFetch
activate Browser
deactivate Browser
@enduml
